### ISSUE TITLE
Uncaught TypeError: Object #<Object> has no method 'success'

### ISSUE THREAD

**Issue by tomascassidy** [SaneMethod/jquery-ajax-localstorage-cache#12]
When I try to use this with jQuery 1.8.3, I get the following error:

Uncaught TypeError: Object #<Object> has no method 'success'

The error is thrown on https://github.com/paulirish/jquery-ajax-localstorage-cache/blob/master/jquery-ajax-localstorage-cache.js#L31

**Comment by kayzee** [comment]
@th3fallen the cache function doesn't work with this solution because it still performs the AJAX call unless you call jqXHR.abort();
