### ISSUE TITLE
Success function array fails: TypeError: object is not a function

### ISSUE THREAD

**Issue by markokeeffe** [SaneMethod/jquery-ajax-localstorage-cache#21]
jQuery.ajax() API allows for an array of success functions to be specified: 

 > As of jQuery 1.5, the success setting can accept an array of functions. Each function will be called in turn.

The following line is incompatible with this:
```js
if ( options.realsuccess ) options.realsuccess( data );
```

**Comment by SaneMethod** [comment]
I think this is moot now, given that adding success callbacks (in an array or otherwise) is deprecated, and that we've added support for jQuery Deferred - you can just hang as many .done or .fail blocks off of the request as you like.
