### ISSUE TITLE
Unmaintained

### ISSUE THREAD

**Issue by paulirish** [SaneMethod/jquery-ajax-localstorage-cache#26]
I haven't touched this project in years. If anyone wants to take on ownership, please email me.

Otherwise, you should probably avoid it. :)

**Comment by SaneMethod** [comment]
I'd be willing to take over this project. I built on it a couple of years ago to add what looks to be the most requested feature in the project's issues - adding support for jQuery Deferred (see http://artandlogic.com/2013/06/ajax-caching-transports-compatible-with-jquery-deferred/). 

One of the commentors let me know this repo is currently unmaintained, and asked if I'd take it over - let me know your preference.

**Comment by paulirish** [comment]
sounds good!

![image](https://cloud.githubusercontent.com/assets/39191/8047665/38f2b384-0dfd-11e5-8545-0d4254f77b38.png)

**Comment by paulirish** [comment]
nice work so far!

i would recommend emailing github support to ask them to break the fork chain

so that it doesnt look like this is a plain fork of another repo.
