### ISSUE TITLE
Possible bug with a user passing an object via localCache that isn't an instance of Storage

### ISSUE THREAD

**Issue by softwarespot** [SaneMethod/jquery-ajax-localstorage-cache#28]
Instead of ...
```
if (!storage) return;
```

use this...

```
// Check if the storage is not an instance of storage
if ((storage instanceof Storage) === false) {
    return;
}
```

PS Awesome you took over the project.

**Comment by softwarespot** [comment]
You can see I have implemented it in my custom fork >> https://github.com/softwarespot/jquery-ajax-localstorage-cache

**Comment by SaneMethod** [comment]
We shouldn't drop the ```if (!storage) return;``` check, as that's part of preventing the rest of the ajaxprefilter logic from executing when options.localCache is false or undefined.

Another part of the reasoning behind this form of the check is to allow users to pass in objects that implement the storage interface duck-wise (i.e. has a getItem, setItem, clear, etc. function), but doesn't have the Storage interface anywhere in its prototype chain. It's not a major change, but if we do require that storage be an instance of Storage, the change should probably be written into the documentation. I'll consider it.

**Comment by softwarespot** [comment]
Okay, I understand your reasoning why you wouldn't want this. But the limitation still remains that getItem()/setItem() must exist. So how about this instead?

```
If (!('getItem' in storage) || !('setItem' in storage)) return;
```

I haven't checked all the polyfills out there that emulate session/localStorage, but I'm sure someone somewhere has implemented their own variation, without paying close attention to the specification. So for some unsuspecting user, who feels they have what is required to use the following library, will get a shock when they see some "unknown function" message.

**Comment by SaneMethod** [comment]
That looks pretty good, but rather than simply ```return```, I'd suggest we ```throw``` instead (or indeed, simply leave non-standard conforming polyfills to fail when ```getItem``` or ```setItem``` is called and not found). 

I'm currently of the opinion that a noisy error message is precisely what's called for when a developer attempts to use a non-standard polyfill with Jalc, as opposed to silently failing to cache requested values as expected. That way it's clear the polyfill is the problem, rather than some failure in Jalc. 

I'm open to being convinced otherwise, though.

**Comment by softwarespot** [comment]
I wouldn't be opposed to throwing an error, it makes sense in this case.

**Comment by softwarespot** [comment]
Did you want me to submit a PR?

**Comment by SaneMethod** [comment]
That's okay, I'll get this one. Let me know if you see any issues with the change.
