### ISSUE TITLE
window is not scoped

### ISSUE THREAD

**Issue by softwarespot** [SaneMethod/jquery-ajax-localstorage-cache#34]
```
; (function($, window, undefined) {
```
Something like this is recommended. I am not submitting as a PR, until I know you're okay with this.

**Comment by SaneMethod** [comment]
I'm okay with passing window into the closure if you desire, although I don't feel it necessary - I'd be interested in hearing your rationale for why you'd recommend this.

I don't believe undefined is used anywhere in the code currently, so there's no need to define it as a parameter for now; and I typically prefer to test against ```void(0)``` myself, although that's just personal preference, as it eliminates issues with undefined (the variable so named) being potentially assigned a value other than ```undefined```.

**Comment by softwarespot** [comment]
Fair enough about undefined. I would use void 0, but it can often be unreadable for those who don't quite understand its intentions. About passing window to the closure, it's slightly faster than using implied globals, as there is less work for the interpreter to "walk the scope chain".

**Comment by SaneMethod** [comment]
Good point - if you'd like to submit a PR, I'll review and merge it.
