### ISSUE TITLE
'toLowerCase' error during ajax call.

### ISSUE THREAD

**Issue by akshayashet** [SaneMethod/jquery-ajax-localstorage-cache#37]
Hi,

I am getting this error after ajax call. 

Code : 
$(function(){
$.ajax({
        url          : 'https://api.myjson.com/bins/wmg5',
        localCache   : true,        // Required. Either a boolean, in which case localStorage will be used, or an object that implements the Storage interface.

        cacheTTL     : 1,           // Optional. In hours.
        cacheKey     : 'POST',      // optional.
        isCacheValid : function(){  // optional.
            return true;
        }
    }).done(function(response){
        response.map(function(i,val){
            $('.container').append("<div>"+val.first_name+"</div")
        });
    });
});

error : 
![image](https://cloud.githubusercontent.com/assets/3539011/13358392/12dd5bde-dcd5-11e5-9259-a50cc1bd5065.png)

Please help me to solve the issue.

Thanks

**Comment by thinkdj** [comment]
I am facing the same. jQuery-1.12.2 and jalc.

**Comment by thinkdj** [comment]
Woot! Thanks, @SaneMethod

**Comment by SaneMethod** [comment]
You're welcome. :)

Note that I decided against my original approach (requiring that dataType be specified in the options when making a request for cached data if you wanted json deserialized) and pushed another patch - you'll want the more recent code, so you can avoid nesting your request in conditionals if you decide to omit the 'dataType' parameter (but see the new note in the README - you'll get more consistent results if you just specify the expected return dataType in your $.ajax call).

**Comment by thinkdj** [comment]
Roger that. I had made a make-shift patch by manually specifying 'json' for dataType before your commit.
