### ISSUE TITLE
default cacheKey function fails

### ISSUE THREAD

**Issue by johnv-git** [SaneMethod/jquery-ajax-localstorage-cache#46]
The default cacheKey generation fails for GET requests because the options url/data pair is mutated between the call to ajaxPrefilter and ajaxTransport.

In ajaxPrefilter():

- options.type = GET
- options.url = /path/to/api/method
- options.data = p1=param1&p2=param2

In ajaxTransport():

- options.type = GET
- options.url = /path/to/api/method?p1=param1&p2=param2&_=1489431445387
- options.data = undefined

So the default cacheKey of (url + type + data) yields:
ajaxPrefilter => /path/to/api/methodGETp1=param1&p2=param2
ajaxTransport => /path/to/api/method?p1=param1&p2=param2GET

This cacheKey function works nicely for both GET and POST requests.
return options.type + url + (options.data ? '?' + options.data : '');

**Comment by SaneMethod** [comment]
@johnv-git This is resolved as of 42c87b7. If you're still seeing this using an up-to-date version of the plugin, please open a new issue, and link to a test case where the issue can be seen.

**Comment by johnv-git** [comment]
Sorry about that, I hadn't noticed you'd chosen to store the generated key value in the options object!
